### PR TITLE
Simple Validator for Command mailcoach:make-user

### PR DESCRIPTION
**Pull request by drjdr**
When butterfly keyboards enter key press gets stuck it gives you some empty password trouble in creating a user...

### CODE REVIEW

**Comment by freekmurze** [comment]
@drjdr Could you add a test for this?

**Comment by riasvdv** [comment]
@drjdr Thanks for the PR, looks good, is there a reason you needed to change composer.json? Could you remove that change?

**Comment by drjdr** [comment]
composer could not find a solvable version set ar that time to run the tests if I remember well, will verify tonight.

**Comment by riasvdv** [comment]
Added in 4.0.2

**Pull request closed without merging**
